# Minimal Kafka KRaft Setup - Single Node
# This node acts as both controller and broker

# Enable KRaft mode (no ZooKeeper)
kraft:
  enabled: true

# Controller configuration (also acts as broker)
controller:
  replicaCount: 1
  persistence:
    enabled: false
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  # Make this controller also handle broker traffic
  controllerOnly: false

# Disable separate broker nodes (controller handles this)
broker:
  replicaCount: 0

# Ensure ZooKeeper is disabled
zookeeper:
  enabled: false

# Disable authentication for simplicity
auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  sasl:
    enabled: false
  tls:
    enabled: false

# Service configuration
service:
  type: ClusterIP
  
# Disable external access for minimal setup
externalAccess:
  enabled: false

# Minimal JVM settings
heapOpts: "-Xmx256m -Xms256m"

# Enable JMX for metrics collection (demo)
metrics:
  jmx:
    enabled: true
    service:
      port: 9999

# Additional security settings - disable all authentication
listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT

# Disable SASL completely
sasl:
  enabled: false
