
kraft:
  enabled: true

# Controller configuration (also acts as broker)
controller:
  replicaCount: 1
  persistence:
    enabled: false
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  controllerOnly: false

broker:
  replicaCount: 0

zookeeper:
  enabled: false

auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  sasl:
    enabled: false
  tls:
    enabled: false

service:
  type: ClusterIP
  
externalAccess:
  enabled: false

heapOpts: "-Xmx256m -Xms256m"

metrics:
  jmx:
    enabled: true
    service:
      port: 9999

listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT

sasl:
  enabled: false
