apiVersion: v1
kind: Service
metadata:
  name: dice-app-service
  namespace: kloudmate
  labels:
    app: dice-app
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: dice-app

---
apiVersion: v1
kind: Service
metadata:
  name: dice-app-external
  namespace: kloudmate
  labels:
    app: dice-app
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
    protocol: TCP
    name: http
  selector:
    app: dice-app
