apiVersion: v1
kind: Service
metadata:
  name: otel-collector-service
  namespace: kloudmate
  labels:
    app: otel-collector
spec:
  type: ClusterIP
  ports:
  - port: 4317
    targetPort: 4317
    protocol: TCP
    name: otlp-grpc
  - port: 4318
    targetPort: 4318
    protocol: TCP
    name: otlp-http
  selector:
    app: otel-collector

---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-external
  namespace: kloudmate
  labels:
    app: otel-collector
spec:
  type: NodePort
  ports:
  - port: 4317
    targetPort: 4317
    nodePort: 30317
    protocol: TCP
    name: otlp-grpc
  - port: 4318
    targetPort: 4318
    nodePort: 30318
    protocol: TCP
    name: otlp-http
  selector:
    app: otel-collector
