apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: kloudmate
  labels:
    app: otel-collector
data:  
  config.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    
    receivers:
      # Application telemetry from Flask app
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
        # Basic Kubernetes metrics (demo)
      kubeletstats:
        collection_interval: 60s
        auth_type: "serviceAccount"
        endpoint: "https://${env:K8S_NODE_NAME}:10250"
        insecure_skip_verify: true
    
    processors:
      batch:
        send_batch_size: 5000
        timeout: 10s
    
    exporters:
      debug:
        verbosity: detailed
      otlphttp:
        endpoint: https://otel.kloudmate.com:4318
        headers:
          Authorization: sk_3ZP4Cj0xMNEOuEkN10NybLC0
        tls:
          insecure: false
        timeout: 30s
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
    
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, otlphttp]
        metrics:
          receivers: [otlp, kubeletstats]
          processors: [batch]
          exporters: [debug, otlphttp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, otlphttp]
